### ISSUE TITLE
Allow setting configuration options on a `mubot.toml` file

### ISSUE THREAD

**Issue by cfcosta** [mugraph-payments/mubot#6]
Example:

```toml
[mubot]
model = "ollama/llama3.1:1b"
```
